# Generated by Django 5.0.14 on 2025-07-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_empleado_delete_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='NOMBRE',
        ),
    ]
