# Generated by Django 5.0.14 on 2025-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_nombre_empleado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='NOMBRE',
            field=models.CharField(db_column='NOMBRE', max_length=100),
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='NOMBRE',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(db_column='APELLIDO', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(db_column='EMAIL', max_length=254),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(db_column='SALARIO', decimal_places=2, max_digits=10),
        ),
    ]
