# Generated by Django 5.0.14 on 2025-07-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_empleado_nombre_rename_nombre_empleado_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
    ]
