# Generated by Django 5.0.14 on 2025-07-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_empleado_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(db_column='ID_EMPLEADO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NOMBRE', max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='APELLIDO', max_length=25, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EMAIL', max_length=25, null=True)),
                ('numero_telefono', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NUMERO_TELEFONO', max_length=20, null=True)),
                ('fecha_contrato', models.DateTimeField(blank=True, db_column='FECHA_CONTRATO', null=True)),
                ('salario', models.IntegerField(blank=True, db_column='SALARIO', null=True)),
                ('comision', models.IntegerField(blank=True, db_column='COMISION', null=True)),
                ('id_supervisor', models.IntegerField(blank=True, db_column='ID_SUPERVISOR', null=True)),
                ('id_departamento', models.IntegerField(blank=True, db_column='ID_DEPARTAMENTO', null=True)),
            ],
            options={
                'db_table': 'EMPLEADOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puesto', models.IntegerField(db_column='ID_PUESTO', primary_key=True, serialize=False)),
                ('titulo_puesto', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TITULO_PUESTO', max_length=35, null=True)),
                ('salario_minimo', models.IntegerField(blank=True, db_column='SALARIO_MINIMO', null=True)),
                ('salario_maximo', models.IntegerField(blank=True, db_column='SALARIO_MAXIMO', null=True)),
            ],
            options={
                'db_table': 'PUESTOS',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
