# Generated by Django 5.0.14 on 2025-07-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_empleados_puestos_delete_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puestos',
        ),
    ]
