# Generated by Django 5.0.14 on 2025-07-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_delete_puestos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puesto', models.CharField(db_column='ID_PUESTO', max_length=10, primary_key=True, serialize=False)),
                ('titulo_puesto', models.CharField(blank=True, db_column='TITULO_PUESTO', max_length=35, null=True)),
                ('salario_minimo', models.IntegerField(blank=True, db_column='SALARIO_MINIMO', null=True)),
                ('salario_maximo', models.IntegerField(blank=True, db_column='SALARIO_MAXIMO', null=True)),
            ],
            options={
                'db_table': 'PUESTOS',
                'managed': False,
            },
        ),
    ]
