# Generated by Django 5.0.14 on 2025-07-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_puestos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.CharField(db_column='ID_DEPARTAMENTO', max_length=10, primary_key=True, serialize=False)),
                ('titulo_puesto', models.CharField(blank=True, db_column='NOMBRE_DEPARTAMENTO', max_length=35, null=True)),
                ('salario_minimo', models.IntegerField(blank=True, db_column='ID_SUPERVISOR', null=True)),
                ('salario_maximo', models.IntegerField(blank=True, db_column='ID_LOCACION', null=True)),
            ],
            options={
                'db_table': 'DEPARTAMENTOS',
                'managed': False,
            },
        ),
    ]
