# Generated by Django 5.0.14 on 2025-07-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_departamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locaciones',
            fields=[
                ('id_locacion', models.CharField(db_column='ID_LOCACION', max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=40, null=True)),
                ('codigo', models.CharField(blank=True, db_column='CODIGO_POSTAL', max_length=12, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='CIUDAD', max_length=30, null=True)),
                ('provincia', models.CharField(blank=True, db_column='PROVINCIA', max_length=25, null=True)),
                ('id_pais', models.CharField(blank=True, db_column='ID_PAIS', max_length=2, null=True)),
            ],
            options={
                'db_table': 'LOCACIONES',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='puestos',
            options={'managed': True},
        ),
    ]
