# Generated by Django 5.0.14 on 2025-07-31 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_locaciones_alter_departamentos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentos',
            old_name='titulo_puesto',
            new_name='nombre_departamento',
        ),
        migrations.RemoveField(
            model_name='departamentos',
            name='salario_maximo',
        ),
        migrations.RemoveField(
            model_name='departamentos',
            name='salario_minimo',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='id_locacion',
            field=models.ForeignKey(blank=True, db_column='ID_LOCACION', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.locaciones'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='id_supervisor',
            field=models.ForeignKey(blank=True, db_column='ID_SUPERVISOR', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.empleados'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_puesto',
            field=models.ForeignKey(blank=True, db_column='ID_PUESTO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.puestos'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_departamento',
            field=models.ForeignKey(blank=True, db_column='ID_DEPARTAMENTO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.departamentos'),
        ),
    ]
