# Generated by Django 5.0.14 on 2025-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_rename_titulo_puesto_departamentos_nombre_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='id_supervisor',
            field=models.IntegerField(blank=True, db_column='ID_SUPERVISOR', null=True),
        ),
    ]
